import type { DestinationDetail } from "../components/DestinationDetailModal";

export type LocalDest = DestinationDetail & {
  img: string;
  badge: string;
  nights: string;
  stars: number;
  rating: number;
  desc: string;
  country: string;
};

function parsePrice(price: string): number {
  return parseInt(price.replace(/[^0-9]/g, "")) || 0;
}

export const letovanjaSrbija: LocalDest[] = [
  {
    name: "Zlatibor — Hotel Mona",
    img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=80"],
    price: "149€", nights: "7 noći", stars: 4, rating: 4.7,
    badge: "Polupansion", destinationType: "letovanje",
    desc: "Predivni planinski vazduh i kristalno čisto jezero. Idealno za porodice i parove.",
    country: "Srbija",
    location: "Zlatibor, Srbija — 1000m nadmorske visine",
    aboutDestination: "Zlatibor je planinska idila u zapadnoj Srbiji na nadmorskoj visini od 1000m. Zlatibor jezero je popularno za kupanje, ribolov i vožnju čamcem. Čuveni Drvengrad i Šarganska osmica su u blizini.",
    aboutHotel: "Hotel Mona Zlatibor je moderan 4-zvezdan resort u srcu Zlatibora, 200m od jezera. Wellness centar sa unutrašnjim bazenom, saunama i jacuzzijem.",
    rooms: "Standardne sobe (26m²) sa balkonom. Porodični apartmani (45m²). Predsednički apartman (80m²).",
    facilities: ["Unutrašnji bazen 25m", "Jacuzzi", "Sauna", "Masaže", "Teretana", "Teniski teren", "Wi-Fi", "Parking"],
    tip: "Posetite Drvengrad i Mećavnik Emira Kusturice — etno-selo od starih drvenih kuća, 20 min vožnje.",
    includes: ["Polupansion", "Bazen", "Spa & Wellness", "Planinarski izleti", "Parking"],
    available: ["Jul 1–8", "Jul 15–22", "Aug 5–12", "Aug 20–27"],
  },
  {
    name: "Vrnjačka Banja — Wellness Spa",
    img: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80"],
    price: "129€", nights: "5 noći", stars: 4, rating: 4.6,
    badge: "All Inclusive", destinationType: "letovanje",
    desc: "Oporavite se u srpskoj spa prestorici. Termalne vode, masaže i zdrava hrana.",
    country: "Srbija",
    location: "Vrnjačka Banja, centralna Srbija",
    aboutDestination: "Vrnjačka Banja je srpska prestonica zdravlja i najposećenija banja Srbije sa 7 lekovitih mineralnih izvora.",
    aboutHotel: "Wellness Spa hotel 4* u srcu banje, 200m od šetališta. Kompletan wellness program sa medicinskim tretmanima.",
    rooms: "Standardne sobe (24m²) sa minibarom. Superior sobe sa termalnim kupatilom.",
    facilities: ["Termalni bazeni", "Wellness 600m²", "Medicinski spa", "Masaže", "Sauna", "Restoran", "Wi-Fi", "Parking"],
    tip: "5-noćni wellness paket sa 2 masaže i 3 banjska tretmana — idealno za regeneraciju i detoks.",
    includes: ["All Inclusive", "Termalni bazen", "Wellness", "Masaža", "Rekreacija"],
    available: ["Jun 10–15", "Jul 3–8", "Aug 1–6", "Sep 5–10"],
  },
  {
    name: "Tara — Eko Resort",
    img: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80"],
    price: "119€", nights: "5 noći", stars: 3, rating: 4.5,
    badge: "Noćenje+Doručak", destinationType: "letovanje",
    desc: "Idiličan eko-odmor u srcu Tare. Šetnje, raftning i organska hrana.",
    country: "Srbija",
    location: "Nacionalni park Tara, Bajina Bašta",
    aboutDestination: "Nacionalni park Tara je najočuvaniji zeleni park Srbije. Kanjon reke Drine i raftning su top atrakcije.",
    aboutHotel: "Eko Resort od domaćeg drveta, 30 bungalova. 100% organska hrana sa sopstvene ekofarm.",
    rooms: "Drveni bungalovi (35m²) sa terasom i pećnicom na drva. Standardne sobe u glavnoj zgradi.",
    facilities: ["Eko-restoran", "Rafting", "Trekking", "Bicikli", "Jahanje", "BBQ"],
    tip: "Rafting na kanjonu Drine — ture traju 4–6 sati kroz jedinstven kanjon dostupan isključivo rekom.",
    includes: ["Doručak", "Rafting", "Trekking", "Bicikli", "BBQ večeri"],
    available: ["Jun 20–25", "Jul 10–15", "Aug 10–15"],
  },
];

export const letovanjaInostranstvo: LocalDest[] = [
  {
    name: "Grčka — Krf, Hotel Dassia Beach",
    img: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1586500036706-41963de24d8b?w=600&q=80"],
    price: "349€", nights: "7 noći", stars: 5, rating: 4.9,
    badge: "All Inclusive", destinationType: "letovanje",
    desc: "Kristalno plava voda Jonskog mora, maslinjaci i autentična grčka kuhinja. Charter let iz Beograda.",
    country: "Grčka",
    location: "Uvala Dasija, Krf (Corfu), Jonsko More",
    aboutDestination: "Krf je najzeleniji grčki ostrvo u Jonskom moru. Grad Kerkira je UNESCO svetska baština.",
    aboutHotel: "Hotel Dassia Beach 5* direktno uz plažu u uvali Dasija. 280 soba, AI, aqua park.",
    rooms: "Standardne sobe (22–28m²) sa balkonom. Porodični apartmani (35–42m²).",
    facilities: ["Bazen 25m", "Dečiji bazen", "Aqua park", "Animacija", "Tenis", "Wi-Fi", "Parking"],
    beach: "Šljunkovito-peščana plaža 800m direktno ispred hotela.",
    tip: "Celonevni izlet brodom do Paleokastritsa sa zaustavljanjem u ribarskoj taverni.",
    includes: ["All Inclusive", "Charter let", "Transfer", "Animacija", "Aqua park"],
    available: ["Jun 8–15", "Jun 22–29", "Jul 6–13", "Jul 20–27", "Aug 3–10"],
  },
  {
    name: "Turska — Antalija, Club Hotel",
    img: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80"],
    price: "299€", nights: "7 noći", stars: 5, rating: 4.8,
    badge: "Ultra All Inclusive", destinationType: "letovanje",
    desc: "Pored tirkiznog Mediteranskog mora sa 5* uslugom. Beskonačni bazeni i water park.",
    country: "Turska",
    location: "Konyaaltı, Antalija, Turska",
    aboutDestination: "Antalija je prestonica turske rivijere sa 300 km plaža okruženih Tauruskim planinama.",
    aboutHotel: "Club Hotel 5* Ultra AI. Vodeni park sa 12 tobogana, lazy river 150m, 4 restorana, spa 1500m².",
    rooms: "Standardne sobe (30m²). Porodične sobe (48m²). Family suite (65m²).",
    facilities: ["UAI 24h", "Vodeni park", "Lazy River", "4 bazena", "Kids club", "Hamam", "5 restorana"],
    beach: "Šljunkovita plaža Konyaaltı 7 km. Besplatni shuttle 30 min.",
    tip: "Poseta antičkom Aspendosu — organizovani transfer svakog dana u 09:30.",
    includes: ["Ultra All Inclusive", "Charter let", "Transfer", "Kids club", "Water park"],
    available: ["Jun 1–8", "Jun 15–22", "Jul 1–8", "Jul 15–22", "Aug 1–8", "Aug 15–22"],
  },
  {
    name: "Egipat — Hurgada, Arabela Resort",
    img: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1546948630-b2aefd08f3fa?w=600&q=80"],
    price: "449€", nights: "10 noći", stars: 5, rating: 4.7,
    badge: "All Inclusive", destinationType: "letovanje",
    desc: "Ronite u Crvenom moru i istražujte faraonsku civilizaciju. Koralni grebeni uz hotel.",
    country: "Egipat",
    location: "Safaga Bay, Hurgada, Egipat, Crveno more",
    aboutDestination: "Hurgada je egipatsko odmaralište na Crvenom moru sa koralnim grebenima i vidljivošću do 30m.",
    aboutHotel: "Arabela Resort 5* u zaštićenoj uvali, sopstvena koralna plaža, PADI ronilački centar.",
    rooms: "Standardne sobe (32m²). Sea view bungalovi (48m²).",
    facilities: ["3 olimpijska bazena", "Privatna koralna plaža", "PADI centar", "Desert Safari", "4 restorana", "Hamam"],
    beach: "Privatna koralna plaža, greben na 15m od obale. Snorkelovanje sa plaže.",
    tip: "PADI Open Water kurs u 3 dana — postajete sertifikovani ronilac. Grupni kursevi od 150€.",
    includes: ["All Inclusive", "Charter let", "Transfer", "Ronjenje", "Desert Safari"],
    available: ["Jun 5–15", "Jul 3–13", "Aug 7–17", "Sep 2–12"],
  },
  {
    name: "Španija — Kosta del Sol, Playa Resort",
    img: "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1559825481-12a05cc00344?w=600&q=80"],
    price: "389€", nights: "7 noći", stars: 4, rating: 4.8,
    badge: "Hotel+Let", destinationType: "letovanje",
    desc: "Sunčana Costa del Sol sa 300 sunčanih dana godišnje. Flamenko večeri i vrhunska ishrana.",
    country: "Španija",
    location: "Torremolinos, Kosta del Sol, Španija",
    aboutDestination: "Kosta del Sol — 160 km zlatnih plaža, andaluzijska sela, flamenko i tapas kultura.",
    aboutHotel: "Playa Resort direktno na zlatnoj plaži Torremolinos-a. Infinity bazen, restoran u Michelin vodiču.",
    rooms: "Standard sea view (28m²). Junior suite (45m²). Deluxe suite (55m²) sa jacuzzijem.",
    facilities: ["Infinity bazen", "Direktna plaža", "Michelin restoran", "Spa", "Tenis", "Wi-Fi"],
    beach: "Zlatna plaža Torremolinos, Mediteran 26°C u leto.",
    tip: "Caminito del Rey — staza u kanjonu — je nezaboravan doživljaj, 1h od hotela.",
    includes: ["Hotel 4*", "Avio karta", "Transfer", "Tapas večeri", "Aquapark"],
    available: ["Jun 10–17", "Jul 8–15", "Aug 5–12", "Aug 26–Sep 2"],
  },
];

export const zimovanjaSrbija: LocalDest[] = [
  {
    name: "Kopaonik — Grand Hotel & Spa",
    img: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1542332213-31f87348e0a4?w=600&q=80"],
    price: "339€", nights: "7 noći", stars: 5, rating: 4.9,
    badge: "All Inclusive", destinationType: "zimovanje",
    desc: "Najveće srpsko skijalište sa 55km staza direktno ispred hotelskih vrata. Olimpijski Spa.",
    country: "Srbija",
    location: "Kopaonik, centralna Srbija — 1770m n.v.",
    aboutDestination: "Kopaonik je najveće skijalište Srbije sa 55km staza i 40 ski-liftova. Nadmorska visina 1770m.",
    aboutHotel: "Grand Hotel & Spa 5* direktno na ski stazi. Spa 1200m², olimpijski bazen, 4 saune.",
    rooms: "Klasična soba (30m²). Deluxe suite (55m²) sa kaminom. Planinska villa (90m²).",
    facilities: ["Direktan izlaz na ski stazu", "Olimpijski bazen 25m", "SPA 1200m²", "4 saune", "Ski škola"],
    tip: "Rezervišite ski školu za decu mesec dana unapred — kursevi se pune brzo.",
    includes: ["All Inclusive", "Ski pass", "Ski škola", "SPA", "Oprema", "Transfer"],
    available: ["Dec 27–Jan 3", "Jan 10–17", "Jan 24–31", "Feb 7–14", "Feb 21–28", "Mar 7–14"],
  },
  {
    name: "Zlatibor — Mona Hotel Snow",
    img: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=600&q=80"],
    price: "149€", nights: "5 noći", stars: 4, rating: 4.7,
    badge: "Polupansion", destinationType: "zimovanje",
    desc: "Zimska bajka na Zlatiboru. Gondola žičara, sanka staza i bazen sa pogledom na sneg.",
    country: "Srbija",
    location: "Zlatibor, Srbija — Tornik ski centar, 1496m n.v.",
    aboutDestination: "Zlatibor zimi — Tornik ski centar sa gondolom i snowboard parkom. Sanka staza 1.5km.",
    aboutHotel: "Mona Hotel Snow 4*, 1km od ski lifta Tornik. Unutrašnji bazen 32°C sa pogledom na sneg.",
    rooms: "Standardna soba (26m²). Deluxe sa fireplace-om (32m²). Apartman (45m²).",
    facilities: ["Unutrašnji bazen 32°C", "Finska sauna", "Ski room", "Restoran", "Parking", "Shuttle"],
    tip: "Iznajmite sanjke za decu — sanka staza 1.5km, bezbedna za porodice.",
    includes: ["Polupansion", "Ski pass Tornik", "Bazen", "Shuttle", "Parking"],
    available: ["Dec 26–31", "Jan 5–10", "Jan 18–23", "Feb 1–6", "Feb 15–20", "Mar 1–6"],
  },
  {
    name: "Stara Planina — Ski Jablaničko",
    img: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80"],
    price: "119€", nights: "5 noći", stars: 3, rating: 4.5,
    badge: "Noćenje+Doručak", destinationType: "zimovanje",
    desc: "Neotkrivena zimska destinacija. Autentična planinska atmosfera, manje gužve i pristupačne cene.",
    country: "Srbija",
    location: "Stara Planina, istočna Srbija — 1700m n.v.",
    aboutDestination: "Stara Planina — Jablaničko skijalište 12km staza, sneg od novembra do aprila. Etno-sela.",
    aboutHotel: "Planinska kuća 3* sa 40 soba. Restoran sa planinskim jelima. Sauna i mini-wellness.",
    rooms: "Standardne sobe (20m²). Sobe sa kaminom (25m²). Drvene kolibe (40m²).",
    facilities: ["Sauna", "Restoran", "Ski room", "Wi-Fi", "Parking", "Shuttle"],
    tip: "Rent sanjke i trasa do etno-sela — kačamak i rakija kakvi se ne mogu naći drugde.",
    includes: ["Noćenje+Doručak", "Sauna", "Parking", "Transfer do lifta"],
    available: ["Dec 28–Jan 2", "Jan 12–17", "Feb 2–7", "Feb 16–21", "Mar 2–7"],
  },
];

export const zimovanjaInostranstvo: LocalDest[] = [
  {
    name: "Slovenija — Kranjska Gora",
    img: "https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=600&q=80"],
    price: "279€", nights: "5 noći", stars: 4, rating: 4.7,
    badge: "Polupansion", destinationType: "zimovanje",
    desc: "Porodično skijalište 3km od Italije. Jasna ski centar i Vitranc kup Svetskog kupa.",
    country: "Slovenija",
    location: "Kranjska Gora, Slovenija — Triglavski nacionalni park",
    aboutDestination: "Kranjska Gora je alpski dragulj, domaćin Vitranc kupa. Jasna ski centar 26km staza.",
    aboutHotel: "Hotel Larix 4*, 5min od ski lifta. Bazen 29°C, sauna, wellness.",
    rooms: "Standardne sobe (26m²). Deluxe (34m²). Apartmani (50m²).",
    facilities: ["Bazen 29°C", "Sauna", "Wellness", "Ski room", "Restoran", "Parking", "Shuttle"],
    tip: "Rent-a-car — za 30 min ste u Udine (Italija) ili Villach (Austrija).",
    includes: ["Polupansion", "Ski pass Jasna", "Bazen & sauna", "Transfer", "Parking"],
    available: ["Dec 27–Jan 1", "Jan 10–15", "Jan 24–29", "Feb 7–12", "Feb 21–26"],
  },
  {
    name: "Austrija — Innsbruck Ski Resort",
    img: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600&q=80"],
    price: "649€", nights: "7 noći", stars: 4, rating: 4.8,
    badge: "Hotel+Let", destinationType: "zimovanje",
    desc: "Olimpijska prestonica Tirola. 300+ km staza, Stubai Glacier i barokni Innsbruck.",
    country: "Austrija",
    location: "Innsbruck, Tirol, Austrija",
    aboutDestination: "Innsbruck — dvaput domaćin Zimskih olimpijada. 6 ski oblasti, 300+ km staza.",
    aboutHotel: "Hotel Alpine Lodge 4*, 10min od Marktplatz. Wellness, sauna, jacuzzi, austrijski restoran.",
    rooms: "Standardne sobe (28–32m²). Deluxe (42m²). Porodične sobe (48m²).",
    facilities: ["Ski-bus card", "Ski room", "Wellness", "Sauna", "Jacuzzi", "Austrijski restoran"],
    tip: "Stubai Glacier — skijanje čak i u maju na 3200m. Celonevni izlet sa vodičem.",
    includes: ["Hotel 4*", "Avio karta", "Transfer", "Ski-bus card", "Sauna & wellness"],
    available: ["Dec 21–28", "Jan 4–11", "Jan 18–25", "Feb 8–15", "Feb 22–Mar 1"],
  },
  {
    name: "Italija — Dolomiti, Val Gardena",
    img: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80"],
    price: "979€", nights: "7 noći", stars: 5, rating: 4.9,
    badge: "All Inclusive", destinationType: "zimovanje",
    desc: "UNESCO Dolomiti i legendarni Sellaronda ski karusel. Ladin kultura i fine dining.",
    country: "Italija",
    location: "Ortisei, Val Gardena, Trentino-Alto Adige, Italija",
    aboutDestination: "Dolomiti — UNESCO baština. Sellaronda karusel 26km. Ladin kultura.",
    aboutHotel: "Hotel Tyrol 5* u Ortisei. Sopstveni ski-lift, outdoor jacuzzi, fine dining.",
    rooms: "Sobe (32–75m²) sa balkonima i pogledom na Dolomite. Porodični suite (80m²).",
    facilities: ["Direktni ski-lift", "Outdoor jacuzzi", "Indoor bazen", "SPA 900m²", "Fine dining"],
    tip: "Sellaronda — krenite SUPROTNO od oznaka za manje gužve na liftovima.",
    includes: ["All Inclusive", "Ski pass Dolomiti Superski", "Direktni ski-lift", "SPA", "Fine dining"],
    available: ["Dec 22–29", "Jan 3–10", "Jan 17–24", "Feb 7–14", "Feb 21–28"],
  },
  {
    name: "Švajcarska — Verbier",
    img: "https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=80"],
    price: "1199€", nights: "7 noći", stars: 5, rating: 5.0,
    badge: "VIP paket", destinationType: "zimovanje",
    desc: "Jetset skijalište sveta sa 412 km staza. Butler usluga i privatni ski instruktor.",
    country: "Švajcarska",
    location: "Verbier, Valais, Švajcarska",
    aboutDestination: "Verbier — globalna prestonica elitnog skijanja. 4 Vallées, 412km staza.",
    aboutHotel: "Chalet RoyAlp 5*, 50m od gondole. 65 chalet suita, privatni butler 24/7.",
    rooms: "Chalet Suite (55–90m²). Royal Suite (150m²) sa privatnim jacuzzijem.",
    facilities: ["Butler 24/7", "Privatni ski instruktor", "Indoor & outdoor bazeni", "Medical SPA", "Fine dining"],
    tip: "Off-piste freeride u Val de Bagnes — netaknuti prah sneg uz privatnog vodiča.",
    includes: ["Hotel 5*", "Avio karta", "Privatni transfer", "Ski pass 4 Vallées", "Butler", "Instrukcija"],
    available: ["Dec 20–27", "Jan 3–10", "Jan 24–31", "Feb 14–21"],
  },
];

export const hoteli: LocalDest[] = [
  {
    name: "Ikos Aria — Kos, Grčka",
    img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=600&q=80"],
    price: "599€", nights: "7 noći", stars: 5, rating: 5.0,
    badge: "Luxury All Inclusive", destinationType: "hotel",
    desc: "Pobednik World Travel Awards za 5. uzastopnu godinu. Privatna plaža i 9 restorana bez doplata.",
    country: "Grčka",
    location: "Kefalos Bay, Kos, Dodekanez, Grčka",
    aboutDestination: "Kos — najzeleniji u Egejskom moru, rodni grad Hipokrata. Kefalos Bay sa turbo-plavom vodom.",
    aboutHotel: "Ikos Aria — najnagrađivaniji AI resort u Evropi. Infinite Lifestyle™, privatna plaža 400m.",
    rooms: "Deluxe Garden View (50m²). Bungalov uz bazen (65m²). Overwater Suite (95m²).",
    facilities: ["9 restorana bez doplata", "Infinity bazen 50m", "Privatna plaža", "Spa 2000m²", "Svi vodeni sportovi besplatno"],
    beach: "Privatna plaža Kefalos Bay, zlatni pesak, SUP, kajak i jedrilica besplatno.",
    tip: "Overwater Suite sa staklenim podom — jedinstven doživljaj spavanja iznad Egejskog mora.",
    includes: ["Infinite Lifestyle AI", "Premium minibar", "Svi vodeni sportovi", "9 restorana", "Spa"],
    available: ["Jun 1–8", "Jun 15–22", "Jul 6–13", "Jul 20–27", "Aug 10–17"],
  },
  {
    name: "Jumeirah Burj Al Arab — Dubai",
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1495482432709-455f228a40d7?w=600&q=80"],
    price: "1499€", nights: "5 noći", stars: 5, rating: 5.0,
    badge: "7★ Jedinstven", destinationType: "hotel",
    desc: "Jedini 7-zvezdan hotel na svetu. Privatni butler, Rolls-Royce fleet i podmorski restoran sa ajkulama.",
    country: "UAE",
    location: "Jumeirah Beach, Dubai, UAE",
    aboutDestination: "Dubai — Burj Khalifa, Dubai Mall, Palm Jumeirah. Gold Souk i arabijska pustinja.",
    aboutHotel: "Burj Al Arab na privatnom ostrvu. 202 dupleks suita min 170m². Butler, podmorski restoran.",
    rooms: "Deluxe Suite (170m²). Diplomatic Suite (370m²). Sky View Suite (780m²).",
    facilities: ["Butler 24/7", "Rolls-Royce fleet", "Podmorski restoran", "Sky Bar na 200m", "Gold Spa 1700m²", "Privatna plaža"],
    tip: "Ručak u Scape restoranu na 200m visine — pogled na ceo Dubai u sumrak.",
    includes: ["5-noćni boravak", "Butler Service", "Rolls-Royce obilazak", "Spa tretman", "Al Mahara večera"],
    available: ["Tokom cele godine", "Blagdanima uz doplatu"],
  },
  {
    name: "Amansara — Siem Reap, Kambodža",
    img: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    price: "899€", nights: "4 noći", stars: 5, rating: 4.9,
    badge: "Kulturna Perla", destinationType: "hotel",
    desc: "Bivša vila kralja Sihanouka. Privatni pristup Angkor Watu pre turista.",
    country: "Kambodža",
    location: "Siem Reap, Kambodža — 6km od Angkor Wata",
    aboutDestination: "Angkor Wat — najveći verski objekat ikad. Kompleks kmerskih hramova 12. veka, UNESCO.",
    aboutHotel: "Amansara — bivša kraljevska vila. 24 sobe, privatni pristup Angkor kompleksu.",
    rooms: "Suite (100m²) sa privatnim dvorištem, bazenom i verandom.",
    facilities: ["Privatni pristup Angkor Watu", "Personalni vodič-arheolog", "Spa", "Privatni bazen"],
    tip: "Sunrise poseta Angkor Watu u 04:30h — hram se budi u zoru dok magla lebdi nad džunglom.",
    includes: ["Boravak", "Doručak & večera", "Privatni pristup Angkor", "Personalni vodič", "Transfer"],
    available: ["Oktobar–April (sušna sezona)", "Novembar–Februar (idealan period)"],
  },
  {
    name: "Four Seasons — Bora Bora",
    img: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80"],
    price: "1299€", nights: "7 noći", stars: 5, rating: 5.0,
    badge: "Raj na Zemlji", destinationType: "hotel",
    desc: "Overwater bungalovi sa staklenim podom nad tirkiznom lagunom. Medeni mesec destinacija #1.",
    country: "Francuska Polinezija",
    location: "Motu Tehotu, Bora Bora, Francuska Polinezija",
    aboutDestination: "Bora Bora — 'Biser Pacifika'. Laguna proglašena 1 od 7 prirodnih čuda, vidljivost 40m.",
    aboutHotel: "Four Seasons 107 bungalova nad vodom. Stakleni pod, direktan ulaz u lagunom.",
    rooms: "Overwater Bungalov (80m²). Overwater Suite (158m²). Royal Beach Villa (310m²).",
    facilities: ["Overwater bungalovi", "Coral garden snorkeling", "Manta ray swimming", "Spa nad lagunom"],
    beach: "Privatne platforme nad lagunom, direktan ulaz u more iz sobe.",
    tip: "Discover Scuba Diving u 1 dan — vidite mante i morske pse u kristalnoj laguni.",
    includes: ["Bungalov nad lagunom", "Doručak", "Canoe sunrise tura", "Manta ray iskustvo", "Snorkeling"],
    available: ["Tokom cele godine", "Apr–Nov (idealna klima)"],
  },
  {
    name: "Rosewood — Hong Kong",
    img: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1574144113084-b6f450cc5673?w=600&q=80"],
    price: "749€", nights: "4 noći", stars: 5, rating: 4.9,
    badge: "Urban Luxury", destinationType: "hotel",
    desc: "Najviši hotel u Hong Kongu sa panoramom Victoria Harbour i Michelin restoranima.",
    country: "Hong Kong",
    location: "Victoria Dockside, Kowloon, Hong Kong",
    aboutDestination: "Hong Kong — Victoria Harbour, Symphony of Lights, Peak Tram, 83 Michelin zvezde.",
    aboutHotel: "Rosewood 65-spratni toranj na Victoria Dockside. 10 restorana, Asaya Spa 6 etaža.",
    rooms: "Premier Room (60m²). Victoria Harbour Suite (120m²). Asaya Suite (200m²).",
    facilities: ["Pogled na Victoria Harbour", "Asaya Spa 6 etaža", "10 restorana", "Legacy House Michelin ⭐", "Infinity bazen"],
    tip: "Tsim Sha Tsui promenada u 20:00h — Symphony of Lights laserski show, besplatan.",
    includes: ["Boravak", "Doručak za 2", "Spa pristup", "Airport limuzin", "Harbour view"],
    available: ["Tokom cele godine", "Chinese New Year (poseban paket)"],
  },
  {
    name: "Lefay Resort — Lago di Garda, Italija",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80"],
    price: "699€", nights: "5 noći", stars: 5, rating: 4.9,
    badge: "Wellness & Natura", destinationType: "hotel",
    desc: "Talijanski wellness raj nad Gardskim jezerom. Taoistički spa i infinity bazen sa pogledom na Alpe.",
    country: "Italija",
    location: "Gargnano, Lago di Garda, Lombardija, Italija",
    aboutDestination: "Lago di Garda — najveće jezero Italije sa mediteranskom mikroklimom. Dvorac Scaligero, Sirmione.",
    aboutHotel: "Lefay Resort — taoistički wellness resort na obali Gardskog jezera. Spa 3500m², 3 organska restorana.",
    rooms: "Deluxe Terrace Suite (60m²). Suite (85m²) sa kaminom. Grand Suite (120m²) sa jacuzzijem.",
    facilities: ["Taoistički Spa 3500m²", "Infinity bazen", "Indoor bazen", "Tenis", "Yoga & pilates", "3 organska restorana"],
    beach: "Privatni pontoni na jezeru, kayak i SUP besplatno.",
    tip: "Celonevni izlet brodom — Sirmione, Limone sul Garda, ručak u kontobi Bardolino regiona.",
    includes: ["Boravak", "Doručak i večera", "Spa pristup", "Kayak i SUP", "Wellness program"],
    available: ["Apr–Okt (jezero sezona)", "Jun–Aug (idealno)"],
  },
];

export const izleti: LocalDest[] = [
  {
    name: "Drinska klisura — Rafting",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    gallery: [],
    price: "35€", nights: "1 dan", stars: 5, rating: 4.9,
    badge: "Avantura", destinationType: "izlet",
    desc: "Rafting kanjonom Drine — najuzbudljivija vodena avantura u Srbiji. Prelepi kanjoni i kristalna voda.",
    country: "Srbija",
    location: "Kanjon Drine, Bajina Bašta, Srbija",
    aboutDestination: "Kanjon reke Drine je jedan od najdubljih kanjona u Srbiji sa vertikalnim stenama visine 700m.",
    aboutHotel: "Jednodnevni izlet sa polazkom iz Loznice ili Beograda.",
    rooms: "",
    facilities: ["Rafting oprema", "Iskusni vodič", "Ručak u prirodi", "Transfer"],
    tip: "Nosite vodu i sunčanu kremu — tura traje 4–6 sati.",
    includes: ["Rafting oprema", "Vodič", "Ručak", "Transfer"],
    available: ["Maj–Septembar", "Svaki vikend"],
  },
  {
    name: "Đavolja varoš — Mistična Srbija",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    gallery: [],
    price: "25€", nights: "1 dan", stars: 4, rating: 4.7,
    badge: "Kultura", destinationType: "izlet",
    desc: "Posetite čudo prirode — 202 kamene figure. UNESCO tenativna lista i pećine u okolini.",
    country: "Srbija",
    location: "Đavolja varoš, kod Kuršumlije, južna Srbija",
    aboutDestination: "Đavolja varoš — 202 kamene figure visine do 15m, dve izvora kisele i lekovite vode.",
    aboutHotel: "Jednodnevni izlet sa polazkom iz Loznice ili Beograda.",
    rooms: "",
    facilities: ["Vodič", "Ručak", "Transport"],
    tip: "Posetite u popodnevnim satima kada sunce baci senke na figure — magično iskustvo.",
    includes: ["Transport", "Vodič", "Ručak"],
    available: ["Tokom cele godine", "Svake nedelje"],
  },
  {
    name: "Manastiri Fruške Gore",
    img: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&q=80",
    gallery: [],
    price: "30€", nights: "1 dan", stars: 4, rating: 4.6,
    badge: "Verski izlet", destinationType: "izlet",
    desc: "16 manastira u srcu Fruške Gore. Degustacija vina i srpska nacionalna kuhinja.",
    country: "Srbija",
    location: "Fruška Gora, Vojvodina, Srbija",
    aboutDestination: "Fruška Gora — 16 pravoslavnih manastira iz 15–18. veka. Vinogradarski kraj.",
    aboutHotel: "Jednodnevni izlet sa polazkom iz Loznice ili Beograda.",
    rooms: "",
    facilities: ["Vodič", "Degustacija vina", "Srpska kuhinja", "Transport"],
    tip: "Krušedol i Novo Hopovo su najimpresivniji manastiri — počnite od njih.",
    includes: ["Transport", "Vodič", "Degustacija vina", "Ručak"],
    available: ["Tokom cele godine", "Svake subote"],
  },
  {
    name: "Beograd City Tour",
    img: "https://images.unsplash.com/photo-1555990793-da11153b2473?w=600&q=80",
    gallery: [],
    price: "45€", nights: "1 dan", stars: 5, rating: 4.8,
    badge: "City Break", destinationType: "izlet",
    desc: "Kalemegdan, Skadarlija, Savamala i tvrđava. Najuzbudljiviji gradovi Balkana u jednom danu.",
    country: "Srbija",
    location: "Beograd, Srbija",
    aboutDestination: "Beograd — grad na ušću Save i Dunava. Kalemegdanska tvrđava, Skadarlija bohemska četvrt.",
    aboutHotel: "Jednodnevni izlet sa polazkom iz Loznice.",
    rooms: "",
    facilities: ["Vodič", "Prevoz autobusom", "Ručak", "Muzej"],
    tip: "Zalazak sunca sa Kalemegdana nad ušćem Save i Dunava — nema ničeg lepšeg u gradu.",
    includes: ["Transport", "Vodič", "Ručak", "Ulaznica Kalemegdan"],
    available: ["Tokom cele godine", "Svake nedelje"],
  },
];

export const ALL_LOCAL: Record<string, LocalDest[]> = {
  letovanje: [...letovanjaSrbija, ...letovanjaInostranstvo],
  zimovanje: [...zimovanjaSrbija, ...zimovanjaInostranstvo],
  hotel: hoteli,
  izlet: izleti,
};

export { parsePrice };
